version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu/frontend
hooks:
  BeforeInstall:
    - location: scripts/codedeploy_before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/codedeploy_application_start.sh
      timeout: 300
      runas: ubuntu
